# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: shards install # runs during prebuild
    command: shards install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

image:
  file: .gitpod.Dockerfile    

vscode:
  extensions:
    - crystal-lang-tools.crystal-lang
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - mhutchie.git-graph
